package ua.gaponov.posterminal.forms.options;

import com.fazecast.jSerialComm.SerialPort;
import ua.gaponov.posterminal.conf.AppProperties;
import ua.gaponov.posterminal.utils.DialogUtils;

import javax.swing.*;

/**
* @author Andriy Gaponov
*/
public class OptionsForm extends javax.swing.JFrame {


    /**
     * Creates new form OptionsForm
     */
    public OptionsForm() {
        initComponents();
        setImages();
        fillOptions();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsForm frame = new OptionsForm();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    private void setImages() {
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/barcode.png")).getImage());
        cancelButton.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/button_cancel.png")));
        okButton.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/button_ok.png")));
    }

    private void fillOptions() {
        fieldCurrency.setText(AppProperties.getCurrency());
        fieldPrifixWegthBarcode.setText(AppProperties.getWeightItemPrefix());
        fieldIntervalExchange.setText(String.valueOf(AppProperties.getExchangeInterval() / 60000));
        chkExchangeEnable.setSelected(AppProperties.isExchangeEnable());
        fieldShopName.setText(AppProperties.getShopName());
        fieldShopAddress.setText(AppProperties.getShopAddress());
        fieldShopGuid.setText(AppProperties.getShopGuid());
        fieldShopId.setText(String.valueOf(AppProperties.getShopId()));
        fieldCashRegister.setText(AppProperties.getCashRegisterName());
        SerialPort[] ports = SerialPort.getCommPorts();
        for (SerialPort port: ports) {
            comboTerminalPort.addItem(port.getSystemPortName());
            comboDisplayPort.addItem(port.getSystemPortName());
        }
        comboTerminalPort.setSelectedItem(AppProperties.getTerminalPort());
        comboDisplayPort.setSelectedItem(AppProperties.getDisplayPort());
        fldFiscalName.setText(AppProperties.getFiscalName());
        fldFiscalToken.setText(AppProperties.getFiscalToken());
        fldFiscalIp.setText(AppProperties.getFiscalIp());
        fldFiscalAutoSum.setText(String.valueOf(AppProperties.getFiscalAutoPlusMoneySum()));
        fldProstoPayToken.setText(AppProperties.getProstoPayToken());
        fldExchangeFolder.setText(AppProperties.getExchangeFolder());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldCurrency = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPrifixWegthBarcode = new javax.swing.JTextField();
        chkExchangeEnable = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        fieldIntervalExchange = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fldExchangeFolder = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fieldShopName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fieldShopAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fieldShopId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fieldShopGuid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fieldCashRegister = new javax.swing.JTextField();
        comboTerminalPort = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboDisplayPort = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fldFiscalName = new javax.swing.JTextField();
        fldFiscalToken = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fldFiscalIp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fldFiscalAutoSum = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fldProstoPayToken = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Налаштування");
        setResizable(false);

        jLabel1.setText("Валюта");

        jLabel2.setText("Префікс вагового штрихкоду");

        chkExchangeEnable.setText("Обмін включений");

        jLabel3.setText("Інтервал обміну, хв");

        jLabel4.setText("Каталог обміну");

        fldExchangeFolder.setToolTipText("");

        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Назва магазину");

        fieldShopName.setToolTipText("");

        jLabel6.setText("Адреса магазину");

        jLabel7.setText("ID магазину");

        fieldShopId.setToolTipText("");

        jLabel8.setText("GUID магазину");

        fieldShopGuid.setToolTipText("");

        jLabel9.setText("Порт терміналу");

        jLabel10.setText("Назва каси");

        jLabel11.setText("Порт дісплею");

        jLabel12.setText("Ім'я РРО");

        jLabel13.setText("Токен РРО");

        fldFiscalName.setToolTipText("");

        jLabel14.setText("IP РРО");

        jLabel15.setText("Розмінна монета");
        jLabel15.setToolTipText("");

        fldFiscalAutoSum.setToolTipText("Сума яка буде автомтатично внесена в фіскальний реєстратор при відкриті зміни");

        jLabel16.setText("Токен ProstoPay");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkExchangeEnable)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldIntervalExchange, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(fieldPrifixWegthBarcode)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fldProstoPayToken)
                            .addComponent(fieldShopAddress)
                            .addComponent(fieldShopName)
                            .addComponent(fldExchangeFolder)
                            .addComponent(fieldShopGuid)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldShopId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldCashRegister))
                            .addComponent(comboTerminalPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboDisplayPort, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fldFiscalName)
                            .addComponent(fldFiscalToken)
                            .addComponent(fldFiscalIp)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fldFiscalAutoSum, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fieldCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(fieldPrifixWegthBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkExchangeEnable)
                            .addComponent(jLabel3)
                            .addComponent(fieldIntervalExchange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fldExchangeFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(fieldShopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldShopAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldShopId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(fieldCashRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(fieldShopGuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(comboTerminalPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboDisplayPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(fldFiscalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fldFiscalToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fldFiscalIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fldFiscalAutoSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fldProstoPayToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            AppProperties.setWeightItemPrefix(fieldPrifixWegthBarcode.getText());
            AppProperties.setCurrency(fieldCurrency.getText());
            AppProperties.setExchangeInterval(Integer.parseInt(fieldIntervalExchange.getText()) * 60000);
            AppProperties.setExchangeEnable(chkExchangeEnable.isSelected());
            AppProperties.setShopName(fieldShopName.getText());
            AppProperties.setShopAddress(fieldShopAddress.getText());
            AppProperties.setShopGuid(fieldShopGuid.getText());
            AppProperties.setShopId(Integer.parseInt(fieldShopId.getText()));
            AppProperties.setCashRegisterName(fieldCashRegister.getText());
            AppProperties.setTerminalPort((String) comboTerminalPort.getSelectedItem());
            AppProperties.setDisplayPort((String) comboDisplayPort.getSelectedItem());
            AppProperties.setFiscalName(fldFiscalName.getText());
            AppProperties.setFiscalToken(fldFiscalToken.getText());
            AppProperties.setFiscalIp(fldFiscalIp.getText());
            AppProperties.setFiscalAutoPlusMoneySum(Double.parseDouble(fldFiscalAutoSum.getText()));
            AppProperties.setProstoPayToken(fldProstoPayToken.getText());
            AppProperties.setExchangeFolder(fldExchangeFolder.getText());

            dispose();
        } catch (Exception e){
            DialogUtils.error(this, "Помилка збереження налаштувань!");
        }

    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox chkExchangeEnable;
    private javax.swing.JComboBox<String> comboDisplayPort;
    private javax.swing.JComboBox<String> comboTerminalPort;
    private javax.swing.JTextField fieldCashRegister;
    private javax.swing.JTextField fieldCurrency;
    private javax.swing.JTextField fieldIntervalExchange;
    private javax.swing.JTextField fieldPrifixWegthBarcode;
    private javax.swing.JTextField fieldShopAddress;
    private javax.swing.JTextField fieldShopGuid;
    private javax.swing.JTextField fieldShopId;
    private javax.swing.JTextField fieldShopName;
    private javax.swing.JTextField fldExchangeFolder;
    private javax.swing.JTextField fldFiscalAutoSum;
    private javax.swing.JTextField fldFiscalIp;
    private javax.swing.JTextField fldFiscalName;
    private javax.swing.JTextField fldFiscalToken;
    private javax.swing.JTextField fldProstoPayToken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
