package ua.gaponov.posterminal.forms.excise;

import ua.gaponov.posterminal.entity.Language;
import ua.gaponov.posterminal.forms.inputstring.InputStringDialog;
import ua.gaponov.posterminal.utils.BarcodeConverter;

import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;

import javax.swing.*;
import java.awt.event.KeyEvent;

import static ua.gaponov.posterminal.utils.ImagesUtils.getIcon;
import static ua.gaponov.posterminal.utils.ImagesUtils.getImage;

/**
 * @author Andriy Gaponov
 */
public class ExciseScanForm extends javax.swing.JDialog {

    private static StringBuilder barBufer = new StringBuilder();
    private String barcode;
    private boolean ok;

    /**
     * Creates new form exciseScanForm
     */
    public ExciseScanForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    public ExciseScanForm(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
    }
    private void init() {
        initComponents();
        setImages();
        refresh();
        ok = false;
        barcode = null;
    }

    private void refresh() {
        java.awt.EventQueue.invokeLater(() -> fieldBarcode.requestFocus());
    }

    private void setImages() {
        this.setIconImage(getImage("barcode.png"));
        okButton.setIcon(getIcon("button_ok.png"));
        cancelButton.setIcon(getIcon("button_cancel.png"));
    }

    private void getBarcode(KeyEvent evt) {
        if (evt.getKeyCode() == 10) {
            barcodeHandle(barBufer.toString());
            barBufer.setLength(0);
        } else {
            barBufer.append(evt.getKeyChar());
        }
        refresh();
    }

    private void barcodeHandle(String barcode) {
        barcode = barcode.replaceAll("[^A-Za-zА-Яа-я0-9]", "");
        barcode = BarcodeConverter.convertToLatin(barcode);
        fieldBarcode.setText(barcode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        fieldBarcode = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        manualTextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Акцизна марка");

        fieldBarcode.setToolTipText("");
        fieldBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fieldBarcodeKeyPressed(evt);
            }
        });

        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okButtonMouseClicked(evt);
            }
        });

        manualTextButton.setText("Ввести вручну");
        manualTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manualTextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manualTextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manualTextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldBarcodeKeyPressed
        fieldBarcode.setText(null);
        getBarcode(evt);
    }//GEN-LAST:event_fieldBarcodeKeyPressed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okButtonMouseClicked
        ok = true;
        barcode = fieldBarcode.getText();
        dispose();
    }//GEN-LAST:event_okButtonMouseClicked

    private void manualTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manualTextButtonActionPerformed
        InputStringDialog dialog = InputStringDialog.getDialog(this, fieldBarcode.getText(), Language.EN);
        dialog.setVisible(true);
        if (dialog.isOk()) {
            fieldBarcode.setText(dialog.getInputString());
        }
    }//GEN-LAST:event_manualTextButtonActionPerformed

    public boolean isOK() {
        return ok;
    }
    
    public String getExcise() {
        return barcode;
    }
    
    public static ExciseScanForm getBarcode(Component parent) {
        Window window = SwingUtilities.windowForComponent(parent);

        ExciseScanForm dialog;
        if (window instanceof Frame) {
            dialog = new ExciseScanForm((Frame) window, true);
        } else {
            dialog = new ExciseScanForm((Dialog) window, true);
        }
        dialog.init();
        dialog.setLocationRelativeTo(null);
        dialog.applyComponentOrientation(parent.getComponentOrientation());
        return dialog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField fieldBarcode;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton manualTextButton;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
