/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ua.gaponov.posterminal.forms.shiftresult;

import ua.gaponov.posterminal.conf.AppProperties;
import ua.gaponov.posterminal.entity.shift.ShiftResultService;
import ua.gaponov.posterminal.entity.shift.ShiftResultTotal;
import ua.gaponov.posterminal.utils.DateUtils;
import ua.gaponov.posterminal.utils.RoundUtils;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author wmcon
 */
public class ShiftResultForm extends javax.swing.JDialog {

    /**
     * Creates new form ShiftResultForm
     */

    public ShiftResultForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    public ShiftResultForm(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
    }

    private void init() {
        initComponents();
        setImages();
    }

    private void setImages() {
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/barcode.png")).getImage());
        cnclButton.setIcon(new ImageIcon(getClass().getClassLoader().getResource("images/button_cancel.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cnclButton = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblMoneyStart = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();
        lblreturns = new javax.swing.JLabel();
        lblCash = new javax.swing.JLabel();
        lblMoneyOut = new javax.swing.JLabel();
        lblMoneyEnd = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();
        lblMoneyIn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Стан зміни");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Початок зміни");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Користувач");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Залишок на початок");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Продаж");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Повернення");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Виручка готівкою");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Виручка картка");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Службова видача");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Службове внесення");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Залишок в касі");

        cnclButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnclButtonActionPerformed(evt);
            }
        });

        lblDate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDate.setText("17.05.2023 8:30");

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser.setText("Адміністратор");

        lblMoneyStart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMoneyStart.setText("0.00");

        lblSales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSales.setText("0.00");

        lblreturns.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblreturns.setText("0.00");

        lblCash.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCash.setText("0.00");

        lblMoneyOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMoneyOut.setText("0.00");

        lblMoneyEnd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMoneyEnd.setText("0.00");

        lblCard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCard.setText("0.00");

        lblMoneyIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMoneyIn.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cnclButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(lblMoneyEnd)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate)
                            .addComponent(lblMoneyStart)
                            .addComponent(lblSales)
                            .addComponent(lblreturns)
                            .addComponent(lblCash)
                            .addComponent(lblMoneyOut)
                            .addComponent(lblCard)
                            .addComponent(lblMoneyIn)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)))
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblMoneyStart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblreturns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblMoneyOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblMoneyIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblMoneyEnd))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cnclButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnclButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnclButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cnclButtonActionPerformed

    public static ShiftResultForm showDialog(Component parent) {
        Window window = SwingUtilities.windowForComponent(parent);

        ShiftResultForm dialog;
        if (window instanceof Frame) {
            dialog = new ShiftResultForm((Frame) window, true);
        } else {
            dialog = new ShiftResultForm((Dialog) window, true);
        }
        dialog.init();

        dialog.lblDate.setText(ShiftResultService.getShiftStartDate());
        dialog.lblUser.setText(ShiftResultService.getShiftStartUserName());
        dialog.lblMoneyStart.setText(ShiftResultService.getStartSumSafe() + " " + AppProperties.currency);
        dialog.lblMoneyEnd.setText(ShiftResultService.getTotalSumSafe() + " " + AppProperties.currency);

        ShiftResultTotal shiftTotals = ShiftResultService.getShiftTotals(
                DateUtils.getDateTimeNow("yyyy-MM-dd 00:00:00"),
                DateUtils.getDateTimeNow("yyyy-MM-dd 23:59:59")
        );

        dialog.lblSales.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaSale())));
        dialog.lblreturns.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaReturn())));
        dialog.lblCash.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaOrderCash()- shiftTotals.getSummaReturnCash())));
        dialog.lblCard.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaOrderCard())));
        dialog.lblMoneyIn.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaMoneyMoveIn())));
        dialog.lblMoneyOut.setText(String.valueOf(RoundUtils.roundHalfUp(shiftTotals.getSummaMoneyMoveOut())));

        dialog.setLocationRelativeTo(null);
        dialog.applyComponentOrientation(parent.getComponentOrientation());
        return dialog;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cnclButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblCash;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMoneyEnd;
    private javax.swing.JLabel lblMoneyIn;
    private javax.swing.JLabel lblMoneyOut;
    private javax.swing.JLabel lblMoneyStart;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblreturns;
    // End of variables declaration//GEN-END:variables
}
