/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ua.gaponov.posterminal.forms.fiscal;

import ua.gaponov.posterminal.conf.AppProperties;
import ua.gaponov.posterminal.devices.fiscal.DeviceFiscalPrinter;
import ua.gaponov.posterminal.devices.fiscal.vchasno.VchasnoFiscal;
import ua.gaponov.posterminal.documents.orders.OrderService;
import ua.gaponov.posterminal.utils.DialogUtils;

import javax.swing.*;

/**
 *
 * @author wmcon
 */
public class FiscalForm extends javax.swing.JDialog {

    private DeviceFiscalPrinter fiscal = new VchasnoFiscal(AppProperties.fiscalName, AppProperties.fiscalToken);

    /**
     * Creates new form FiscalForm
     */
    public FiscalForm() {
        setModal(true);
        initComponents();
        setImages();
        updateStatus();
    }

    private void updateStatus(){
        String shiftStatus = "Зміна закрита";
        btnCloseShift.setEnabled(false);
        btnOpenShift.setEnabled(false);
        if (fiscal.shiftIsOpen()){
            double safeMoney = fiscal.getSafeMoney();
            shiftStatus = "Зміна відкрита. В сейфі " + safeMoney + " " + AppProperties.currency;
            btnCloseShift.setEnabled(true);

        }else{
            btnOpenShift.setEnabled(true);
        }
        lblShiftInfo.setText(shiftStatus);
    }

    private void setImages() {
        this.setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/barcode.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnOpenShift = new javax.swing.JButton();
        btnCloseShift = new javax.swing.JButton();
        btnMoneyMinus = new javax.swing.JButton();
        fldSum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnMoneyPlus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblShiftInfo = new javax.swing.JLabel();
        btnXReport = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Управління фіскальним реєстратором");
        setResizable(false);

        btnOpenShift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnOpenShift.setText("Відкрити зміну");
        btnOpenShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenShiftActionPerformed(evt);
            }
        });

        btnCloseShift.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCloseShift.setText("Закрити зміну");
        btnCloseShift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseShiftActionPerformed(evt);
            }
        });

        btnMoneyMinus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoneyMinus.setText("Службова видача");
        btnMoneyMinus.setToolTipText("");
        btnMoneyMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyMinusActionPerformed(evt);
            }
        });

        jLabel1.setText("Сума");

        btnMoneyPlus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMoneyPlus.setText("Службове внесення");
        btnMoneyPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyPlusActionPerformed(evt);
            }
        });

        jLabel2.setText("Статус зміни");

        lblShiftInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblShiftInfo.setToolTipText("");

        btnXReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXReport.setText("X-звіт");
        btnXReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnOpenShift, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnCloseShift, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btnMoneyMinus, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fldSum))
                    .addComponent(btnMoneyPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShiftInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXReport, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShiftInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnOpenShift, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCloseShift, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXReport, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fldSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoneyMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMoneyPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenShiftActionPerformed
        fiscal.openShift();
        updateStatus();
        //fiscal.printOrder(OrderService.getByGuid("ec2b65a8-b2b8-4100-87c3-dcdb66bc4b3d"));
    }//GEN-LAST:event_btnOpenShiftActionPerformed

    private void btnCloseShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseShiftActionPerformed
        fiscal.printZReport();
        updateStatus();
    }//GEN-LAST:event_btnCloseShiftActionPerformed

    private void btnMoneyMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyMinusActionPerformed
        try {
            double money = Double.parseDouble(fldSum.getText());
            if (fiscal.moneyMinus(money)) {
                DialogUtils.ok(null, "Службова видача виконана");
                updateStatus();
            } else {
                DialogUtils.error(null, "Помилка видачі");
            }
        } catch (Exception e){
            //NOP
        }
    }//GEN-LAST:event_btnMoneyMinusActionPerformed

    private void btnMoneyPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyPlusActionPerformed
        try {
            double money = Double.parseDouble(fldSum.getText());
            if (fiscal.moneyPlus(money)) {
                DialogUtils.ok(null, "Службове внесення виконано");
                updateStatus();
            } else {
                DialogUtils.error(null, "Помилка внесення");
            }
        } catch (Exception e){
            //NOP
        }
    }//GEN-LAST:event_btnMoneyPlusActionPerformed

    private void btnXReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXReportActionPerformed
        fiscal.printXReport();
    }//GEN-LAST:event_btnXReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FiscalForm frame = new FiscalForm();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseShift;
    private javax.swing.JButton btnMoneyMinus;
    private javax.swing.JButton btnMoneyPlus;
    private javax.swing.JButton btnOpenShift;
    private javax.swing.JButton btnXReport;
    private javax.swing.JTextField fldSum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblShiftInfo;
    // End of variables declaration//GEN-END:variables
}
